global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'product-service:8081'
          - 'order-service:8082'

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']