server:
  http_listen_port: 3200
  grpc_listen_port: 4317
  http_listen_address: 0.0.0.0
  grpc_listen_address: 0.0.0.0

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

overrides:
  metrics_generator_processors: []
